<?php
function gb_group_members_permission() {
	return array (
			'gb_group_members_per_add' => array (
					'title' => 'Create form gb_group_members According To choice',
					'description' => 'Form gb_group_members Creation' 
			),
			'gb_group_members_per_view' => array (
					'title' => 'View The List Of gb_group_members',
					'description' => 'View gb_group_members according to his powers' 
			) 
	);
}
function gb_group_members_menu() {
	$items ['admins/gb_group_members/add'] = array (
			'title' => 'Add New Gb Group Members Form',
			'page callback' => 'drupal_get_form',
			'page arguments' => array (
					0 => 'gb_group_members_add' 
			),
			'access arguments' => array (
					0 => 'gb_group_members_per_add' 
			),
			'description' => 'General',
			'type' => 0,
			'weight' => 1 
	);
	$items ['admins/gb_group_members/view'] = array (
			'title' => 'Gb Group Members List',
			'page callback' => 'drupal_get_form',
			'page arguments' => array (
					0 => 'gb_group_members_view' 
			),
			'access arguments' => array (
					0 => 'gb_group_members_per_view' 
			),
			'description' => 'General',
			'type' => 0,
			'weight' => 1 
	);
	$items ['admins/gb_group_members/edit/%'] = array (
			'title' => 'Gb Group Members Edit',
			'page callback' => 'drupal_get_form',
			'page arguments' => array (
					0 => 'gb_group_members_add',
					1 => 3 
			),
			'access arguments' => array (
					0 => 'gb_group_members_per_add' 
			),
			'description' => 'General',
			'type' => 0,
			'weight' => 1 
	);
	$items ['admins/gb_group_members/detail/%'] = array (
			'title' => 'Gb Group Members detail',
			'page callback' => 'drupal_get_form',
			'page arguments' => array (
					0 => 'gb_group_members_detail',
					1 => 3 
			),
			'access arguments' => array (
					0 => 'gb_group_members_per_view' 
			),
			'description' => 'General',
			'type' => 0,
			'weight' => 1 
	);
	return $items;
}
function gb_group_members_add($form, &$form_state, $id = NULL) {
	if (! empty ( $id )) {
		$data = get_data_by_pks ( 'gb_group_members', $id );
		
		$form ['#submit'] [] = "gb_group_members_edit_submit";
		$form ['id'] = array (
				'#type' => 'value',
				'#value' => $id 
		);
	}
	$form ['rid'] = array (
			'#type' => 'select',
			'#title' => 'Rid',
			'#options' => array (
					'' => NULL 
			),
			'#attributes' => array (
					'placeholder' => '' 
			),
			'#default_value' => isset ( $data->rid ) ? $data->rid : "" 
	);
	$form ['g_id'] = array (
			'#type' => 'select',
			'#title' => 'G_id',
			'#options' => array (
					'' => NULL 
			),
			'#attributes' => array (
					'placeholder' => '' 
			),
			'#default_value' => isset ( $data->g_id ) ? $data->g_id : "" 
	);
	$form ['created'] = array (
			'#type' => 'textfield',
			'#title' => 'Created',
			'#size' => '10',
			'#attributes' => array (
					'placeholder' => '',
					'maxlength' => '10' 
			),
			'#default_value' => isset ( $data->created ) ? date ( "Y-m-d", $data->created ) : "" 
	);
	$form ['updated'] = array (
			'#type' => 'textfield',
			'#title' => 'Updated',
			'#size' => '10',
			'#attributes' => array (
					'placeholder' => '',
					'maxlength' => '10' 
			),
			'#default_value' => isset ( $data->updated ) ? date ( "Y-m-d", $data->updated ) : "" 
	);
	$form ['updatedby'] = array (
			'#type' => 'textfield',
			'#title' => 'Updatedby',
			'#size' => '10',
			'#attributes' => array (
					'placeholder' => '',
					'maxlength' => '10' 
			),
			'#default_value' => isset ( $data->updatedby ) ? $data->updatedby : "" 
	);
	$form ['createdby'] = array (
			'#type' => 'textfield',
			'#title' => 'Createdby',
			'#size' => '10',
			'#attributes' => array (
					'placeholder' => '',
					'maxlength' => '10' 
			),
			'#default_value' => isset ( $data->createdby ) ? $data->createdby : "" 
	);
	
	$form ['submit'] = array (
			'#type' => 'submit',
			'#value' => 'Save' 
	);
	return $form;
}
function gb_group_members_validate($form, &$form_state) {
}
function gb_group_members_add_submit($form, &$form_state) {
	global $user;
	$query = db_insert ( 'gb_group_members' )->fields ( array (
			'rid' => $form_state ['values'] ['rid'],
			'g_id' => $form_state ['values'] ['g_id'],
			'created' => strtotime ( $form_state ['values'] ['created'] ),
			'updated' => strtotime ( $form_state ['values'] ['updated'] ),
			'updatedby' => $form_state ['values'] ['updatedby'],
			'createdby' => $form_state ['values'] ['createdby'] 
	) )->execute ();
	if ($query > 0) {
		drupal_set_message ( 'gb_group_members added successfully' );
		drupal_goto ( 'admins/gb_group_members/view' );
	}
}
function gb_group_members_edit_submit($form, &$form_state) {
	global $user;
	$query = db_update ( 'gb_group_members' )->fields ( array (
			'rid' => $form_state ['values'] ['rid'],
			'g_id' => $form_state ['values'] ['g_id'],
			'created' => strtotime ( $form_state ['values'] ['created'] ),
			'updated' => strtotime ( $form_state ['values'] ['updated'] ),
			'updatedby' => $form_state ['values'] ['updatedby'],
			'createdby' => $form_state ['values'] ['createdby'] 
	) )->condition ( 'id', $form_state ['values'] ['id'], '=' )->execute ();
	if ($form_state ['values'] ['id'] > 0) {
		drupal_set_message ( 'gb_group_members update successfully' );
		// drupal_goto('admins/gb_group_members/view');
	}
}
function gb_group_members_view($form, &$form_state) {
	global $user;
	$default_rid = '';
	$default_g_id = '';
	
	if (! empty ( $_GET ['rid'] )) {
		$default_rid = $_GET ['rid'];
	}
	if (! empty ( $_GET ['g_id'] )) {
		$default_g_id = $_GET ['g_id'];
	}
	
	$form ['search_form'] = array (
			'#title' => t ( 'Search and SortOrder' ),
			'#type' => 'fieldset',
			'#collapsible' => TRUE,
			'#collapsed' => TRUE,
			'#attached' => array (
					'library' => array (
							array (
									'system',
									'drupal.collapse' 
							) 
					) 
			) 
	);
	
	$form ['search_form'] ['rid'] = array (
			'#type' => 'textfield',
			'#title' => t ( 'RID' ),
			'#size' => 30,
			'#default_value' => $default_rid 
	);
	$form ['search_form'] ['g_id'] = array (
			'#type' => 'textfield',
			'#title' => t ( 'Group Id' ),
			'#size' => 30,
			'#default_value' => $default_g_id 
	);
	
	$form ['search_form'] ['submit'] = array (
			'#type' => 'submit',
			'#value' => 'Submit' 
	);
	$query = db_select ( 'gb_group_members', 'tn' )->extend ( 'PagerDefault' )->fields ( 'tn' )->orderBy ( 'tn.gm_id', 'asc' )->limit ( 20 );
	if (! empty ( $default_rid )) {
		
		$query->condition ( 'tn.rid', $default_rid, '=' );
	}
	if (! empty ( $default_g_id )) {
		$query->condition ( 'tn.g_id', $default_g_id, '=' );
	}
	$result = $query->execute ();
	$rows_articles = array ();
	foreach ( $result as $records ) {
		$created = util_date_format_short ( $records->created );
		//$updated = util_date_format_short ( $records->updated );
		/*
		 * if($records->deleted){
		 * $deleted="Deleted";
		 * }
		 * else
		 * {
		 * $deleted=l("<i class='icon-fixed-width icon-trash'></i>Delete",'admins/gb_group_members/edit/');
		 * }
		 */
		$rows_articles [] = array (
				$records->gm_id,
				$records->rid,
				$records->g_id,
				//$records->created,
				date("Y-m-d",$records->created),
				
			/* 	$records->updated,
				$records->updatedby, */
				$records->createdby 
		);
	}
	$headers = array (
			'Id',
			'Member Id',
			'Group Id',
			'Created',
		/* 	'Updated',
			'Updatedby', */
			'Createdby' 
	);
	$all_articles = theme ( 'table', array (
			'header' => $headers,
			'rows' => $rows_articles,
			'empty' => 'No Record Found',
			'attributes' => array (
					'class' => array (
							'list-table' 
					),
					'style' => 'width:100%;' 
			) 
	) );
	$all_articles .= theme ( 'pager' );
	$form ['all_articles'] = array (
			'#markup' => $all_articles 
	);
	return $form;
}
function gb_group_members_detail($form, &$form_state, $id = NULL) {
	global $user;
	$query = db_select ( 'gb_group_members', 'tn' )->extend ( 'PagerDefault' )->fields ( 'tn' )->condition ( 'tn.id', $id, '=' )->orderBy ( 'tn.id', 'desc' );
	$result = $query->execute ()->fetchObject ();
	$rows_articles = array ();
	if (! empty ( $result ))
		foreach ( $result as $key => $value ) {
			
			$rows_articles [] = array (
					$key . ' :: ' . $value 
			);
		}
	
	$all_articles = theme ( 'table', array (
			'header' => array (),
			'rows' => $rows_articles,
			'empty' => 'No Record Found',
			'attributes' => array (
					'class' => array (
							'list-table' 
					),
					'style' => 'width:100%;' 
			) 
	) );
	$all_articles .= theme ( 'pager' );
	$form ['all_articles'] = array (
			'#markup' => $all_articles 
	);
	return $form;
}
function gb_group_members_view_submit($form, &$form_state) {
	$rid = $form_state ['values'] ['rid'];
	$g_id = $form_state ['values'] ['g_id'];
	
	if (! empty ( $rid )) {
		$param ["rid"] = $rid;
	}
	if (! empty ( $g_id )) {
		$param ["g_id"] = $g_id;
	}
	
	drupal_goto ( 'admins/gb_group_members/view', array (
			'query' => $param 
	) );
}

